language: cpp
dist: trusty
sudo: required
compiler: clang

env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
addons:
  apt:
      sources:  
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
     packages:
      - clang-3.6
      - gcc-5  
      - g++-5  
      - libboost-all-dev  

install: 
  # clang
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 90
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 90
  # clang STL
  - sudo apt-get install -y libc++-dev libc++abi-dev

script:
    - cmake . 
    - make
    - ./testpid  
